GNU_PREFIX = aarch64-linux-gnu
CC = $(GNU_PREFIX)-gcc
LD = $(GNU_PREFIX)-ld
OC = $(GNU_PREFIX)-objcopy

CFLAGS := -mcpu=cortex-a53
OCFLAGS := -O binary

all: kernel8.img

.PHONY: clean
clean:
	rm -rf *.o *.img

%.o: %.S
	$(CC) $(CFLAGS) -c $< -o $@

ASM_FILES = $(wildcard *.S)
OBJ_FILES = $(ASM_FILES:.S=.o)


kernel8.img: linker.ld $(OBJ_FILES)
	$(LD) -T $< -o kernel8.elf $(OBJ_FILES)
	$(OC) $(OCFLAGS) kernel8.elf $@
